version: '3.8'

services:
  app:
    image: smart-last-mile-delivery-system
    ports:
      - "8080:8080" # Thay bằng "8081:8080" nếu cổng 8080 bị chiếm
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/slmds_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2206
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=slmds_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2206
    ports:
      - "5432:5432" # Ánh xạ cổng để debug (có thể bỏ nếu không cần)
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: